### ISSUE TITLE
Consider limiting the maximum pool size

### ISSUE THREAD

**Issue by oddgrd** [aumetra/shuttle-diesel-async#1]
Hey @aumetra, thanks so much for making this, it's really cool! I noticed one thing when looking through this: 

It looks like your are creating a pool with the [default max_size](https://docs.rs/deadpool/0.9.5/deadpool/managed/reexports/struct.PoolConfig.html#impl-Default), this may be a bit much in a shuttle deployment. This is because I believe num_cpus will get all the cores of the host container, even though each deployer is limited to the [equivalent of 4 cores currently](https://github.com/shuttle-hq/shuttle/blob/7c01a7363eaa8d55cc684ed54ad21ea935802a3a/gateway/src/project.rs#L738-L740). Setting it to a lower max should resolve it (shuttle_shared_postgres is capped at 5, since a postgres database has a max limit for connections).
https://github.com/aumetra/shuttle-diesel-async/blob/8ec2577bbf5a41365637759047f9714e694e30ea/src/lib.rs#L88-L97

**Comment by aumetra** [comment]
Makes sense, especially since it's a shared environment. Limited it to 5 (just like `shuttle_shared_postgres`)
